# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Create release branch
        run: git checkout -b release/BuildTest
        
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      # Runs a set of commands using the runners shell
      - name: Add file
        run: touch i
        
      - name: commit
        run: |
          git add i
          git commit --message "Test"
          
      - name: push
        run: git push origin release/BuildTest
        
      - name: create PR
        run: |
          gh pr create -t "Preparing for" -b "build"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
